name: CD
on:
  workflow_run:
    workflows: ["CI"]       # <--- Espera a que el workflow CI termine
    types:
      - completed            # <--- Solo cuando CI haya terminado

jobs:
  cd:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # <--- Solo si CI pasó runs-on: ubuntu-22.04
    name: Build & Push GitHub Package & Deploy on Render Docker Image
    runs-on: ubuntu-22.04

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ☕ Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
          cache: gradle

      - name: 🔧 Build JAR
        run: ./gradlew clean build -x test

      - name: 🏷️ Extract repository info & version
        run: |
          echo "GHCR_URL=ghcr.io" >> $GITHUB_ENV
          echo "REPOSITORY=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
          echo "VERSION=$(./gradlew -q printVersion)" >> $GITHUB_ENV
        # Si no tienes una task printVersion, puedes usar:
        # echo "VERSION=$(./gradlew -q properties | grep 'version:' | awk '{print $2}')" >> $GITHUB_ENV

      - name: 📦 Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PERSONAL_ACCESS_TOKEN }}

      - name: 🏷️ Extract repository info & version
        run: |
          echo "GHCR_URL=ghcr.io" >> $GITHUB_ENV
          echo "REPOSITORY=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
          # Extraer versión directamente de Gradle
          VERSION=$(./gradlew -q properties | grep '^version:' | awk '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: 🐳 Build & Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.GHCR_URL }}/${{ env.REPOSITORY }}:${{ env.VERSION }}
            ${{ env.GHCR_URL }}/${{ env.REPOSITORY }}:latest

      - name: 🚀 Deploy on Render
        run: |
          curl --fail -X POST "${{ secrets.RENDER_DEPLOY_HOOK_TOKEN }}" \
          && echo "✅ Deployment triggered" \
          || (echo "❌ Deployment failed" && exit 1)